### ISSUE TITLE
执行pnpm dev后进入首页报错

### ISSUE THREAD

**Issue by one0oneChen** [sleep1223/fast-soy-admin#14]
GET http://localhost:9527/src/layouts/base-layout/index.vue?vue&type=style&index=0&lang.scss net::ERR_ABORTED 500 (Internal Server Error)
```
22:39:59 [vite] (client) Pre-transform error: [sass] Can't find stylesheet to import.
  ╷
1 │ @use "./src/styles/scss/global.scss" as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\layouts\base-layout\index.vue 1:1  root stylesheet
  Plugin: vite:css
  File: E:/Github/fastapi-soybean-admin/web/src/layouts/base-layout/index.vue?vue&type=style&index=0&lang.scss:1:1
  [sass] Can't find stylesheet to import.
    ╷
  1 │ @use "./src/styles/scss/global.scss" as *;
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    src\layouts\base-layout\index.vue 1:1  root stylesheet
22:40:02 [vite] Internal server error: [sass] Can't find stylesheet to import.
  ╷
1 │ @use "./src/styles/scss/global.scss" as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\layouts\base-layout\index.vue 1:1  root stylesheet
  Plugin: vite:css
  File: E:/Github/fastapi-soybean-admin/web/src/layouts/base-layout/index.vue?vue&type=style&index=0&lang.scss:1:1
  [sass] Can't find stylesheet to import.
    ╷
  1 │ @use "./src/styles/scss/global.scss" as *;
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    src\layouts\base-layout\index.vue 1:1  root stylesheet
      at Object.wrapException (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:2286:43)
      at E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:87328:25
      at _wrapJsFunctionForAsync_closure.$protected (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5039:15)
      at _wrapJsFunctionForAsync_closure.call$2 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38067:12)
      at _awaitOnObject_closure.call$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38055:32)
      at Object._rootRunUnary (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5461:18)
      at StaticClosure.<anonymous> (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:124056:16)
      at _CustomZone.runUnary$2$2 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:39524:39)
      at _Future__propagateToListeners_handleValueCallback.call$0 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38581:51)
      at Object._Future__propagateToListeners (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5253:93)
      at _Future._completeWithValue$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38439:9)
      at _AsyncAwaitCompleter.complete$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38042:14)
      at Object._asyncReturn (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5011:17)
      at E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:94883:24
      at _wrapJsFunctionForAsync_closure.$protected (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5039:15)
      at _wrapJsFunctionForAsync_closure.call$2 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38067:12)
      at _awaitOnObject_closure.call$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38055:32)
      at Object._rootRunUnary (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5461:18)
      at StaticClosure.<anonymous> (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:124056:16)
      at _CustomZone.runUnary$2$2 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:39524:39)
      at _Future__propagateToListeners_handleValueCallback.call$0 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38581:51)
      at Object._Future__propagateToListeners (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5253:93)
      at _Future._completeWithValue$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38439:9)
      at _AsyncAwaitCompleter.complete$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38042:14)
      at Object._asyncReturn (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5011:17)
      at E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:94974:24
      at _wrapJsFunctionForAsync_closure.$protected (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5039:15)
      at _wrapJsFunctionForAsync_closure.call$2 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38067:12)
      at _awaitOnObject_closure.call$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38055:32)
      at Object._rootRunUnary (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5461:18)
      at StaticClosure.<anonymous> (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:124056:16)
      at _CustomZone.runUnary$2$2 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:39524:39)
      at _Future__propagateToListeners_handleValueCallback.call$0 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38581:51)
      at Object._Future__propagateToListeners (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5253:93)
      at _Future._completeWithValue$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38439:9)
      at _AsyncAwaitCompleter.complete$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38042:14)
      at Object._asyncReturn (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5011:17)
      at E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:84977:24
      at _wrapJsFunctionForAsync_closure.$protected (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5039:15)
      at _wrapJsFunctionForAsync_closure.call$2 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38067:12)
      at _awaitOnObject_closure.call$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38055:32)
      at Object._rootRunUnary (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5461:18)
      at StaticClosure.<anonymous> (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:124056:16)
      at _CustomZone.runUnary$2$2 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:39524:39)
      at _Future__propagateToListeners_handleValueCallback.call$0 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38581:51)
      at Object._Future__propagateToListeners (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:5253:93)
      at _Future._complete$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38431:11)
      at _SyncCompleter.complete$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:38257:10)
      at promiseToFuture_closure1.call$1 (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:44996:22)
      at Object.Primitives_applyFunction (E:\Github\fastapi-soybean-admin\web\node_modules\.pnpm\sass@1.83.0\node_modules\sass\sass.dart.js:2166:30)
22:40:03 [vite] (client) Pre-transform error: [sass] Can't find stylesheet to import.
  ╷
1 │ @use "./src/styles/scss/global.scss" as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\layouts\modules\global-search\components\search-footer.vue 1:1  root stylesheet
  Plugin: vite:css
  File: E:/Github/fastapi-soybean-admin/web/src/layouts/modules/global-search/components/search-footer.vue?vue&type=style&index=0&scoped=03f6386d&lang.scss:1:1
  [sass] Can't find stylesheet to import.
    ╷
  1 │ @use "./src/styles/scss/global.scss" as *;
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    src\layouts\modules\global-search\components\search-footer.vue 1:1  root stylesheet
```

**Comment by sleep1223** [comment]
可能是node版本问题, 请使用node18+
